#!/usr/bin/env python3
"""FamilySpec round-trip regression: golden fixtures -> live approve pipeline -> diff vs expected/.

For each schemas/familyspec/fixtures/golden/*.pred.json:
  1. insert a synthetic upload + 'ready' extraction on the demo project (service-role SQL),
  2. POST /v1/extractions/{id}/approve?chain=1 with the demo publishable key,
  3. fetch the created family's AFIS + QA score,
  4. normalize (family UUID -> <FAMILY_ID>; strip " (N)" unique-name suffix from identity.name
     — the only two volatile fields, see ../fixtures/expected/NORMALIZATION.md),
  5. diff against fixtures/expected/<fixture>.afis.json — ANY difference is a regression;
     investigate, do not rebaseline,
  6. delete every row it created (families, family_validations, jobs, extractions, uploads).

Requires: APEX_DB_URL (service-role Postgres URL, e.g. from Supabase dashboard), psql on PATH,
and network access to the deployed API. Exit 0 = all fixtures match; 1 = drift (diff printed).

The Round 2 baseline in expected/ was generated by exactly this procedure against api v27 and
verified in-database (jsonb equality, 6/6 true — LEDGER Round 2 Cycle 3). Re-run this after any
change to predToAfis, EXTRACTION_SCHEMA, the QA engine, or the schema of record.
"""
import json
import os
import re
import subprocess
import sys
import urllib.request
import uuid
from pathlib import Path

HERE = Path(__file__).resolve().parent
GOLDEN = HERE.parent / "fixtures" / "golden"
EXPECTED = HERE.parent / "fixtures" / "expected"
API = os.environ.get("APEX_API_URL", "https://kdqisuzydkgzkzxlctpv.supabase.co/functions/v1/api")
KEY = os.environ.get("APEX_ANON_KEY", "sb_publishable_n8xDG4wFR656MR419Vlgrg_6lMibnml")
DEMO_PROJECT = "00000000-0000-4000-8000-000000000002"
DEMO_USER = "00000000-0000-4000-8000-000000000001"


def psql(sql: str) -> str:
    url = os.environ.get("APEX_DB_URL")
    if not url:
        sys.exit("APEX_DB_URL not set (service-role Postgres URL); cannot run round-trip.")
    r = subprocess.run(["psql", url, "-qtAX", "-c", sql], capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"psql failed: {r.stderr.strip()}")
    return r.stdout.strip()


def api_post(path: str) -> dict:
    req = urllib.request.Request(API + path, method="POST", data=b"{}",
        headers={"authorization": f"Bearer {KEY}", "content-type": "application/json"})
    with urllib.request.urlopen(req) as resp:
        return json.load(resp)


def normalize(afis: dict, family_id: str) -> dict:
    text = json.dumps(afis).replace(family_id, "<FAMILY_ID>")
    d = json.loads(text)
    d["identity"]["name"] = re.sub(r" \(\d+\)$", "", d["identity"]["name"])
    return d


def main() -> int:
    failures = 0
    for fixture in sorted(GOLDEN.glob("*.pred.json")):
        slug = fixture.name.replace(".pred.json", "")
        exp_path = EXPECTED / f"{slug}.afis.json"
        if not exp_path.exists():
            print(f"SKIP {slug}: no expected file")
            continue
        expected = json.loads(exp_path.read_text())
        doc = fixture.read_text().replace("'", "''")
        exid = str(uuid.uuid4())
        tag = f"rt-{slug}-{exid[:8]}"
        psql(f"""
with up as (insert into uploads (project_id, filename, storage_key, size_bytes, hash_sha256,
  mime_type, status, created_by)
  values ('{DEMO_PROJECT}','{tag}.pdf','submittals/rt/{tag}.pdf',10,md5('{tag}')||md5('x'),
          'application/pdf','ready','{DEMO_USER}') returning id)
insert into extractions (id, upload_id, schema_version, status, claude_result)
select '{exid}', id, '1.0.0', 'ready', '{doc}'::jsonb from up;""")
        try:
            api_post(f"/v1/extractions/{exid}/approve?chain=1")
            row = psql(f"select id::text || '|' || (checklist_result->>'score') || '|' || afis::text "
                       f"from families where extraction_id = '{exid}'")
            fam_id, score, afis_text = row.split("|", 2)
            got = {"qa_score_expected": float(score), "afis": normalize(json.loads(afis_text), fam_id)}
            if got == expected:
                print(f"PASS {slug} (qa {score})")
            else:
                failures += 1
                print(f"FAIL {slug}: round-trip differs from expected — REGRESSION, do not rebaseline")
                for k in ("qa_score_expected",):
                    if got[k] != expected[k]:
                        print(f"  {k}: got {got[k]} want {expected[k]}")
                if got["afis"] != expected["afis"]:
                    print("  afis differs; write both to /tmp and diff:")
                    Path(f"/tmp/rt-{slug}.got.json").write_text(json.dumps(got["afis"], indent=2, sort_keys=True))
                    print(f"  got -> /tmp/rt-{slug}.got.json ; expected -> {exp_path}")
        finally:
            psql(f"""
with f as (select id from families where extraction_id = '{exid}'),
 a as (delete from family_validations where family_id in (select id from f)),
 b as (delete from jobs where entity_id in (select id from f)),
 c as (delete from families where id in (select id from f)),
 d as (delete from extractions where id = '{exid}')
delete from uploads where filename = '{tag}.pdf';""")
    print("ROUND-TRIP:", "ALL PASS" if failures == 0 else f"{failures} FAILURES")
    return 0 if failures == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
